### PR TITLE
Fix autodetection

### PR DESCRIPTION
**Pull request by hurricanehrndz**
Auto-detection is too aggressive, other well know yaml files get picked up.

### CODE REVIEW

**Comment by pearofducks** [comment]
Could you clarify "too aggressive" and what other files are being picked up that shouldn't be?

That function hasn't been touched in over 2 years and no one has had an issue with it amongst quite a lot of users. :)

**Comment by hurricanehrndz** [comment]
Picks up kitchen and Travis files within role directories. This request
allows disabling of the function and also adds check for Travis and kitchen

**Comment by pearofducks** [comment]
I agree this is less than ideal, but I don't agree with solving this by trying to place exceptions for every `*.yaml` that isn't an Ansible file. This can very easily be solved in your own `vimrc` through autocommands and since each individual will have 0-n `*.yaml` they want excepted I think this is the best approach.

**Comment by hurricanehrndz** [comment]
Okay, understood and agreed, can we at least have the option to disable the
included Auto detection. I can not have kitchen and Travis and yaml files
toggling back and forth from file types yaml to yaml.ansible and back to
yaml, it really messes with language servers and trying to get auto
complete working with ansible and so on. Also, I think it is just good
practice to have the Auto commands in Auto group. I can modify it
accordingly if you agree the changes are acceptable.

**Comment by hurricanehrndz** [comment]
While we are chatting I do have another question unrelated. It is in
regards to stephpy/vim-yaml plugin, when used I lose the orange
highlighting like in your example image.

**Comment by pearofducks** [comment]
If it is causing problems with other plugins then sure, we can provide an option to disable ftdetect for Ansible files!

**Comment by hurricanehrndz** [comment]
Thank you, I think adding the au commands to a group for ftdetect will
suffice. I can then use an after plugin to erase the group and develop my
own detection. I really appreciate your help. Keep an eye out on
LanguageClient-neovim, I will be updating the wiki to document code
completion and general yaml linting for ansible.

**Pull request closed without merging**
