### PR TITLE
support lists with string values

### PR DESCRIPTION
**Pull request by KimNorgaard**

### CODE REVIEW

**Comment by pearofducks** [comment]
Can you provide an example of where the current indentation fails that this improves upon? I don't know of any faulty indentation in lists right now.

**Comment by KimNorgaard** [comment]
Right, sorry for being to unspecific :-)

I noticed the problem with specifying role tags like this:

```
# vim: set ft=ansible:
- hosts: all
  
  roles:
    - role: test
      tags: test_role
```

When placing the cursor at the end of `role: test` and pressing enter the indentation level starts at the '-' mark.
When placing the cursor at the end of `tags: test_role` and pressing enter the line is outdented.

With this patch, the behavior is as expected.

**Comment by pearofducks** [comment]
You're right that for the usecase you named this is an improvement. I believe, however, that creating "lists" is far more common in Ansible - and this would break that indentation.

```
roles:
   - role: foo
   - role: bar
```

**Comment by KimNorgaard** [comment]
Actually, I think that if you use that form, the next thing you are likely to write is  another key-value pair (just like with tasks after `name:`). If you just wanted to write a list of roles, you would not explicitly use the 'role:' key, but just list them like this:

```
roles:
  - foo
  - far
```

And that works just fine with this PR.

However, the third possible form does not indent as expected:
```
roles:
    - { role: foo, tags: ['tag1'] }
```
The updated PR is simpler and should cover both use cases.

**Comment by pearofducks** [comment]
You're absolutely right about the list form, I'm at a conference right now and have conference-brain.

But the PR looks great now, thanks for the improvement!

**Pull request merged**
