### PR TITLE
support ultisnips

### PR DESCRIPTION
**Pull request by flisky**
I'll kick off the generated `ansible.snippets` if you don't think it should be in :)

### CODE REVIEW

**Comment by pearofducks** [comment]
Thanks for this! I'll look over it later this week or maybe on the weekend, much appreciated though. :)

**Comment by codeinabox** [comment]
I'd be interested in this feature too.

**Comment by pearofducks** [comment]
Hey @flisky, yeah if you remove the ansible.snippets file then I think this can be merged.

**Comment by flisky** [comment]
Done, and one more action: add the generated snippet file into .gitignore.

**Pull request merged**
